version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: f4372f8eac8c16aa5f00a2e10ec6266ced534f651f89015e5f08b5cdf5aa0ee1
      TERM: dumb

    docker:
      - image: circleci/android:api-27-node8-alpha

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          name: Restore Node Modules
          key: node-modules-{{ checksum "package.json" }}

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          name: Save Node Modules
          paths:
            - node_modules
          key: node-modules-{{ checksum "package.json" }}
      
      - run:
          name: Permissions
          path: android
          command: chmod +x ./gradlew
        
      # Run build
      - restore_cache:
          name: Restore Android SDK Dependencies
          key: android-sdk-dependencies

      - run:
          name: Build
          path: android
          command: ./gradlew assembleRelease

      - save_cache:
          name: Save Android SDK Dependencies
          paths:
            - /usr/local/android-sdk-linux/build-tools/23.0.1
            - /usr/local/android-sdk-linux/platforms/android-23
            - /usr/local/android-sdk-linux/extras/android/m2repository
          key: android-sdk-dependencies

      - store_artifacts:
          path: android/app/build/outputs/apk/app-release.apk
          destination: app-release.apk

      # Setup CC
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      # Run tests
      - run:
          name: Test
          command: |
            ./cc-test-reporter before-build
            yarn test -- --coverage
            ./cc-test-reporter after-build --exit-code $?

