version: 2
jobs:
  build:
    environment:
      TERM: dumb

    docker:
      # specify the version you desire here
      - image: circleci/android:api-23-node8-alpha

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run:
          name: chmod permissions
          path: android
          command: chmod +x ./gradlew
        
      # run build
      - run:
          name: Build
          path: android
          command: ./gradlew assembleRelease

      # run tests
      - run:
          name: Test
          command: yarn test
